# video font
font = "Roboto-Medium.ttf"

# how long to wait between starting FakeYou voice jobs
# (anything shorter than 52 seconds is likely to get rate limited and crash the app)
job_delay = 52

# how long to wait between polling pending FakeYou voice jobs
poll_delay = 12