title="Link and Zelda team up to pour spaghetti o's into King Harkinian's socks."

characters = [
    { name="Zelda", description="Princess Zelda, cartoon, Phillips CDI", voice_token="TM:gtear4je4egc" },
    { name="Link", description="The hero Link, cartoon, happy, Phillips CDI", voice_token="TM:fp4fcyja6mk1" },
    { name="King Harkinian", description="king harkinian, yellow clothes and blond hair, with beard, cartoon, phillips CDI", voice_token="TM:gp1sfafqmcwe"}
]

global_style = "in a castle"

[[lines]]
speaker="Link"
speech="Hey there, Zelda! What're you up to?"

[[lines]]
speaker="Zelda"
speech="Just pourin' some spaghetti o's into King Harkinian's socks. Wanna help?"

[[lines]]
speaker="King Harkinian"
speech="What the-? Hey! My socks!"

[[lines]]
speaker="Zelda"
speech="Oh, did we get your socks wet? We're sorry!"
custom_prompt="Princess Zelda, cartoon, Phillips CDI, laughing"

[[lines]]
speaker="King Harkinian"
speech="No, no, it's quite all right. I just never knew that spaghetti o's could be so... slimy."

[[lines]]
speaker="Zelda"
speech="They're not slimy, they're just wet."
custom_prompt="slimy cartoon socks covered in beans, gross, disgusting, slimy, wet, pasta sauce, juicy, moist, damp"

[[lines]]
speaker="Link"
speech="Yeah, they're just wet. Anyways, we should probably get going."

[[lines]]
speaker="King Harkinian"
speech="Yes, you two should probably be on your way. Thanks for the, uh, experience."

[[lines]]
speaker="Link"
speech="No problem, your majesty. Come on, Zelda."

[[lines]]
speaker="King Harkinian"
speech="Wait! What about my socks?"
custom_prompt="slimy cartoon socks covered in beans, gross, disgusting, slimy, wet, pasta sauce, juicy, moist, damp"

[[lines]]
speaker="Zelda"
speech="Oh, don't worry about them. We'll take care of them."

[[lines]]
speaker="King Harkinian"
speech="Oh, all right. Thanks!"

[[lines]]
speaker="Link"
speech="I'm going to eat them."