# this contains a curated list
# of popular characters
# that work well with stable diffusion
# and FakeYou

[GLaDOS]
image_prompt = "GLaDOS"
default_voice = "TM:fm4h94vk4eem"

["Homer Simpson"]
image_prompt = "Homer Simpson"
default_voice = "TM:r9mxvgcybyy5"

["Samuel L. Jackson"]
image_prompt = "Samuel L. Jackson"
default_voice = "TM:1kxgs8qffn08"

["Morgan Freeman"]
image_prompt = "Morgan Freeman"
default_voice = "TM:709ck7g83431"

[Wallace]
image_prompt = "Wallace adult man (wallace & gromit), claymation, stop motion"
default_voice = "TM:sq8sn457mb63"

[Yugi]
image_prompt = "Yugi, anime, spiky hair"
default_voice = "TM:4khbj8e538c1"

[Shrek]
image_prompt = "Shrek"
default_voice = "TM:2pw2a5drwx49"

[Yoda]
image_prompt = "Yoda"
default_voice = "TM:ydfm7kj9kdwh"

["Weird Al"]
image_prompt = "Wierd Al"
default_voice = "TM:rawayafee2a2"

["Joey Wheeler"]
image_prompt = "joey wheeler, male, anime, spiky hair, blond, bangs, jacket"
default_voice = "TM:9ahjngw6xsc7"

[Mario]
image_prompt = "Mario with red cap and mustache"
default_voice = "TM:c7j599fz0pbg"

[Luigi]
image_prompt = "Luigi with green cap and mustache"
default_voice = "TM:fp4fcyja6mk1"

["Bill Nye"]
image_prompt = "Billy Nye"
default_voice = "TM:3e0wsf4wqcpv"

[Wario]
image_prompt = "Wario"
default_voice = "TM:pwwcbzscesd0"

[Voldemort]
image_prompt = "Voldemort"
default_voice = "TM:nczpqg58jj6n"

[Kurzgesagt]
image_prompt = "kurzgesagt bird with big white eyes, orange feet, after effects, material design, soft shadows, high saturation, rounded edges, smooth"
default_voice = "TM:9msyk3s92yrv"

[Donkey]
image_prompt = "Fuzzy donkey"
default_voice = "TM:9napv5ew50jv"

["Tobey Maguire"]
image_prompt = "Tobey Maguire"
default_voice = "TM:tqp1k2ne5j33"

[Gandhi]
image_prompt = "Mahatma Gandhi"
default_voice = "TM:cvw5qkye9y22"

["Donald Trump"]
image_prompt = "Donald Trump"
default_voice = "TM:4v0ft4j72y2g"

["Barack Obama"]
image_prompt = "Barack Obama"
default_voice = "TM:58vtv7x9f32c"

["Jack Sparrow"]
image_prompt = "Jack Sparrow"
default_voice = "TM:da7yzmfnb8f8"